package modularwotclaninfo;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Yoyo117 (johnp)
 */
public class ClassPanel extends JPanel {

    public static final Color NAME_COLOR = new Color(238,180,34);
    public static final Color NUM_COLOR = new Color(135,206,255);

    private ArrayList<JLabel> names;
    private ArrayList<JLabel> numbers;

    private final String vclass;

    public ClassPanel(String vclass) {
        this(vclass, null);
    }

    public ClassPanel(String vclass, Vehicle[] vehicles) {
        this.vclass = vclass;
        names = new ArrayList<JLabel>(10);
        numbers = new ArrayList<JLabel>(10);
        initComponents();
        this.setLayout(new BoxLayout(this, BoxLayout.X_AXIS));
        this.add(new JLabel(this.getVclass()+":   "));

        if (vehicles != null)
            addVehicles(vehicles);
    }

    public void addVehicle(Vehicle vehicle)
    {
        for (int i = 0; i < getNames().size(); i++) {
            String vn = getNames().get(i).getText();
            vn = vn.substring(0, vn.length()-1); // cut ':'
            if (vehicle.getName().equals(vn)) {
                getNumbers().get(i).setText(" "+Integer.toString(Integer.parseInt(getNumbers().get(i).getText().trim())+1)+"  ");
                return;
            }
        } // else
        JLabel name = new JLabel(vehicle.getName()+":");
        JLabel number = new JLabel(" 1   ");
        name.setForeground(NAME_COLOR);
        number.setForeground(NUM_COLOR);
        this.add(name);
        this.add(number);
        getNames().add(name);
        getNumbers().add(number);
    }

    public void addVehicles(Vehicle[] vehicles)
    {
        for (Vehicle v : vehicles)
            addVehicle(v);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public String getVClass() {
        return getVclass();
    }

    public ArrayList<JLabel> getNames() {
        return names;
    }

    public ArrayList<JLabel> getNumbers() {
        return numbers;
    }

    public String getVclass() {
        return vclass;
    }
}
