package modularwotclaninfo;

import java.awt.Component;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;

/**
 *
 * @author Yoyo117 (johnp)
 */
public class NationPanel extends javax.swing.JPanel {

    private ArrayList<ClassPanel> vclasses;

    private final String nation;

    public NationPanel(String nation) {
        this(nation, null);
    }

    public NationPanel(String nation, Vehicle[] vehicles) {
        this.nation = nation;
        this.vclasses = new ArrayList<ClassPanel>(5);
        initComponents();
        this.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        JLabel nationLabel = new JLabel(this.getNation());
        nationLabel.setFont(new Font("Tahoma", Font.BOLD, 14));
        nationLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        this.add(nationLabel);

        if (vehicles != null)
            addVClasses(vehicles);
    }

    public void addVClass(Vehicle vehicle) {
        for (int i = 0; i < getVclasses().size(); i++) {
            ClassPanel line = getVclasses().get(i);
            if (line != null && vehicle.getVClass().equals(line.getVClass())) {
                line.addVehicle(vehicle);
                return;
            }
        }
        ClassPanel line = new ClassPanel(vehicle.getVClass());
        line.addVehicle(vehicle);
        this.add(line);
        this.add(Box.createVerticalStrut(4));
        getVclasses().add(line);
    }

    public void addVClasses(Vehicle[] vehicles) {
        for (Vehicle v : vehicles)
            addVClass(v);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public String getNation() {
        return nation;
    }

    public ArrayList<ClassPanel> getVclasses() {
        return vclasses;
    }
}
