package modularwotclaninfo;

import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.BoxLayout;

/**
 *
 * @author Yoyo117 (johnp)
 */
public class VehiclePanel extends javax.swing.JPanel {

    private ArrayList<NationPanel> nations;

    public VehiclePanel() {
        this(null);
    }

    public VehiclePanel(ArrayList<Vehicle> vehicles) {
        this.nations = new ArrayList<NationPanel>(6);
        initComponents();
        this.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));

        if (vehicles != null)
            addNations(vehicles);
    }

    public void addNation(Vehicle vehicle) {
        for (int i = 0; i < getNations().size(); i++) {
            NationPanel n = getNations().get(i);
            if (n != null && vehicle.getNation().equals(n.getNation())) {
                n.addVClass(vehicle);
                return;
            }
        }
        NationPanel n = new NationPanel(vehicle.getNation());
        n.addVClass(vehicle);
        this.add(n);
        this.add(Box.createVerticalStrut(1));
        getNations().add(n);
    }

    public void addNations(ArrayList<Vehicle> vehicles) {
        for (Vehicle v : vehicles)
            addNation(v);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public ArrayList<NationPanel> getNations() {
        return nations;
    }

    public void setNations(ArrayList<NationPanel> nations) {
        this.nations = nations;
    }
}
